### ISSUE TITLE
Missing docs. And possibly a bug for a method "get_repos_commits_by_owner_repo"?

### ISSUE THREAD

**Issue by rossanoua** [viletyy/gitea-client#4]
Hi.
Thank you for the nice repo.
Is there some documentation?

And looks like a bug for method "get_repos_commits_by_owner_repo".
I'm trying to use it like this:
client.get_repos_commits_by_owner_repo(@owner, @repo, { "sha" => branch })
and this returns the same result
client.get_repos_commits_by_owner_repo(@owner, @repo, { sha: branch })

and got different results from our Gitea API directly if compare it to results of mentioned method.

**Comment by viletyy** [comment]
> Hi. Thank you for the nice repo. Is there some documentation?
> 
> And looks like a bug for method "get_repos_commits_by_owner_repo". I'm trying to use it like this: client.get_repos_commits_by_owner_repo(@owner, @repo, { "sha" => branch }) and this returns the same result client.get_repos_commits_by_owner_repo(@owner, @repo, { sha: branch })
> 
> and got different results from our Gitea API directly if compare it to results of mentioned method.

the third param should be a total hash, you can use it

`
$client.get_repos_commits_by_owner_repo(@owner, @repo, {query: {sha: branch}})
`
